
[WinEventLog://Security]
index = windows_logs
disabled = false
 
[WinEventLog://System]
index = windows_logs
disabled = false
 
[WinEventLog://Application]
index = windows_logs
disabled = false
 
[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = sysmon_logs
disabled = false
